// Code generated by MockGen. DO NOT EDIT.
// Source: otel.go
//
// Generated by this command:
//
//	mockgen -source=otel.go -destination=../tests/mocks/otel.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	config "github.com/inference-gateway/inference-gateway/config"
	logger "github.com/inference-gateway/inference-gateway/logger"
	otel "github.com/inference-gateway/inference-gateway/otel"
	v1 "go.opentelemetry.io/proto/otlp/collector/metrics/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockOpenTelemetry is a mock of OpenTelemetry interface.
type MockOpenTelemetry struct {
	ctrl     *gomock.Controller
	recorder *MockOpenTelemetryMockRecorder
	isgomock struct{}
}

// MockOpenTelemetryMockRecorder is the mock recorder for MockOpenTelemetry.
type MockOpenTelemetryMockRecorder struct {
	mock *MockOpenTelemetry
}

// NewMockOpenTelemetry creates a new mock instance.
func NewMockOpenTelemetry(ctrl *gomock.Controller) *MockOpenTelemetry {
	mock := &MockOpenTelemetry{ctrl: ctrl}
	mock.recorder = &MockOpenTelemetryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenTelemetry) EXPECT() *MockOpenTelemetryMockRecorder {
	return m.recorder
}

// IngestMetrics mocks base method.
func (m *MockOpenTelemetry) IngestMetrics(ctx context.Context, req *v1.ExportMetricsServiceRequest) otel.IngestResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestMetrics", ctx, req)
	ret0, _ := ret[0].(otel.IngestResult)
	return ret0
}

// IngestMetrics indicates an expected call of IngestMetrics.
func (mr *MockOpenTelemetryMockRecorder) IngestMetrics(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestMetrics", reflect.TypeOf((*MockOpenTelemetry)(nil).IngestMetrics), ctx, req)
}

// Init mocks base method.
func (m *MockOpenTelemetry) Init(arg0 config.Config, arg1 logger.Logger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockOpenTelemetryMockRecorder) Init(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockOpenTelemetry)(nil).Init), arg0, arg1)
}

// RecordRequestDuration mocks base method.
func (m *MockOpenTelemetry) RecordRequestDuration(ctx context.Context, source, provider, model, errorType string, seconds float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordRequestDuration", ctx, source, provider, model, errorType, seconds)
}

// RecordRequestDuration indicates an expected call of RecordRequestDuration.
func (mr *MockOpenTelemetryMockRecorder) RecordRequestDuration(ctx, source, provider, model, errorType, seconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRequestDuration", reflect.TypeOf((*MockOpenTelemetry)(nil).RecordRequestDuration), ctx, source, provider, model, errorType, seconds)
}

// RecordTokenUsage mocks base method.
func (m *MockOpenTelemetry) RecordTokenUsage(ctx context.Context, source, provider, model string, inputTokens, outputTokens int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordTokenUsage", ctx, source, provider, model, inputTokens, outputTokens)
}

// RecordTokenUsage indicates an expected call of RecordTokenUsage.
func (mr *MockOpenTelemetryMockRecorder) RecordTokenUsage(ctx, source, provider, model, inputTokens, outputTokens any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordTokenUsage", reflect.TypeOf((*MockOpenTelemetry)(nil).RecordTokenUsage), ctx, source, provider, model, inputTokens, outputTokens)
}

// RecordToolCall mocks base method.
func (m *MockOpenTelemetry) RecordToolCall(ctx context.Context, source, provider, model, toolType, toolName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordToolCall", ctx, source, provider, model, toolType, toolName)
}

// RecordToolCall indicates an expected call of RecordToolCall.
func (mr *MockOpenTelemetryMockRecorder) RecordToolCall(ctx, source, provider, model, toolType, toolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordToolCall", reflect.TypeOf((*MockOpenTelemetry)(nil).RecordToolCall), ctx, source, provider, model, toolType, toolName)
}

// ShutDown mocks base method.
func (m *MockOpenTelemetry) ShutDown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShutDown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ShutDown indicates an expected call of ShutDown.
func (mr *MockOpenTelemetryMockRecorder) ShutDown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShutDown", reflect.TypeOf((*MockOpenTelemetry)(nil).ShutDown), ctx)
}
