// Code generated by MockGen. DO NOT EDIT.
// Source: otel.go
//
// Generated by this command:
//
//	mockgen -source=otel.go -destination=../tests/mocks/otel.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	config "github.com/inference-gateway/inference-gateway/config"
	gomock "go.uber.org/mock/gomock"
)

// MockOpenTelemetry is a mock of OpenTelemetry interface.
type MockOpenTelemetry struct {
	ctrl     *gomock.Controller
	recorder *MockOpenTelemetryMockRecorder
	isgomock struct{}
}

// MockOpenTelemetryMockRecorder is the mock recorder for MockOpenTelemetry.
type MockOpenTelemetryMockRecorder struct {
	mock *MockOpenTelemetry
}

// NewMockOpenTelemetry creates a new mock instance.
func NewMockOpenTelemetry(ctrl *gomock.Controller) *MockOpenTelemetry {
	mock := &MockOpenTelemetry{ctrl: ctrl}
	mock.recorder = &MockOpenTelemetryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenTelemetry) EXPECT() *MockOpenTelemetryMockRecorder {
	return m.recorder
}

// Init mocks base method.
func (m *MockOpenTelemetry) Init(config config.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockOpenTelemetryMockRecorder) Init(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockOpenTelemetry)(nil).Init), config)
}

// RecordTokenUsage mocks base method.
func (m *MockOpenTelemetry) RecordTokenUsage(ctx context.Context, provider, model string, promptTokens, completionTokens, totalTokens int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordTokenUsage", ctx, provider, model, promptTokens, completionTokens, totalTokens)
}

// RecordTokenUsage indicates an expected call of RecordTokenUsage.
func (mr *MockOpenTelemetryMockRecorder) RecordTokenUsage(ctx, provider, model, promptTokens, completionTokens, totalTokens any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordTokenUsage", reflect.TypeOf((*MockOpenTelemetry)(nil).RecordTokenUsage), ctx, provider, model, promptTokens, completionTokens, totalTokens)
}

// RecordTokenUsageWithTime mocks base method.
func (m *MockOpenTelemetry) RecordTokenUsageWithTime(ctx context.Context, provider, model string, promptTokens, completionTokens, totalTokens int64, queueTime, promptTime, completionTime, totalTime float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordTokenUsageWithTime", ctx, provider, model, promptTokens, completionTokens, totalTokens, queueTime, promptTime, completionTime, totalTime)
}

// RecordTokenUsageWithTime indicates an expected call of RecordTokenUsageWithTime.
func (mr *MockOpenTelemetryMockRecorder) RecordTokenUsageWithTime(ctx, provider, model, promptTokens, completionTokens, totalTokens, queueTime, promptTime, completionTime, totalTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordTokenUsageWithTime", reflect.TypeOf((*MockOpenTelemetry)(nil).RecordTokenUsageWithTime), ctx, provider, model, promptTokens, completionTokens, totalTokens, queueTime, promptTime, completionTime, totalTime)
}
