---
branches:
  - { name: main, prerelease: false, channel: latest }
  - { name: 'rc/*', prerelease: rc, channel: rc }

repositoryUrl: 'https://github.com/inference-gateway/inference-gateway'
tagFormat: 'v${version}'

verifyConditions:
  - '@semantic-release/github'
  - '@semantic-release/git'

plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: 'conventionalcommits'
      releaseRules:
        - { type: 'feat', release: 'minor' }
        - { type: 'impr', release: 'patch' }
        - { type: 'refactor', release: 'patch' }
        - { type: 'perf', release: 'patch' }
        - { type: 'fix', release: 'patch' }
        - { type: 'ci', release: 'patch' }
        - { type: 'docs', release: 'patch' }
        - { type: 'style', release: 'patch' }
        - { type: 'test', release: 'patch' }
        - { type: 'build', release: 'patch' }
        - { type: 'security', release: 'patch' }
        - { type: 'chore', release: 'patch', scope: '!release' }

  - - '@semantic-release/release-notes-generator'
    - preset: 'conventionalcommits'
      presetConfig:
        types:
          - { type: 'feat', section: '✨ Features' }
          - { type: 'impr', section: '🚀 Improvements' }
          - { type: 'refactor', section: '♻️ Improvements' }
          - { type: 'perf', section: '⚡️ Improvements' }
          - { type: 'fix', section: '🐛 Bug Fixes' }
          - { type: 'ci', section: '👷 CI' }
          - { type: 'docs', section: '📚 Documentation' }
          - { type: 'chore', section: '🔧 Miscellaneous' }
          - { type: 'style', section: '🎨 Miscellaneous' }
          - { type: 'test', section: '✅ Miscellaneous' }
          - { type: 'build', section: '🔨 Miscellaneous' }
          - { type: 'security', section: '🔒 Security' }

  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
      changelogTitle: "# Changelog\n\nAll notable changes to this project will be documented in this file."
      verifyConditions: true

  - - '@semantic-release/exec'
    - verifyConditions: 'go mod tidy'
      prepareCmd: |
        sed -i 's/const VERSION = ".*"/const VERSION = "v${nextRelease.version}"/' config/meta.go
        sed -i 's/^version: .*/version: ${nextRelease.version}/' charts/inference-gateway/Chart.yaml
        sed -i 's/^appVersion: .*/appVersion: ${nextRelease.version}/' charts/inference-gateway/Chart.yaml

  - - '@semantic-release/github'
    - assets:
        - CHANGELOG.md
      releasedLabels: ['released']
      releaseNameTemplate: '🚀 Version ${nextRelease.version}'
      releaseBodyTemplate: |
        ${nextRelease.notes}

        ---

        ## 📦 Quick Installation

        ### Binary Installation

        **Install latest version:**
        ```bash
        curl -fsSL https://raw.githubusercontent.com/inference-gateway/inference-gateway/main/install.sh | bash
        ```

        **Install this version:**
        ```bash
        curl -fsSL https://raw.githubusercontent.com/inference-gateway/inference-gateway/main/install.sh | VERSION=v${nextRelease.version} bash
        ```

        **Install to custom directory:**
        ```bash
        curl -fsSL https://raw.githubusercontent.com/inference-gateway/inference-gateway/main/install.sh | INSTALL_DIR=~/.local/bin bash
        ```

        **Verify installation:**
        ```bash
        inference-gateway --version
        ```

        ### Running as a Container (Recommended)

        **Using Docker:**
        ```bash
        docker run -d \
          -p 8080:8080 \
          -e OPENAI_API_KEY=your-api-key \
          ghcr.io/inference-gateway/inference-gateway:${nextRelease.version}
        ```

        **Using Docker Compose:**
        ```bash
        # Download example configuration
        curl -O https://raw.githubusercontent.com/inference-gateway/inference-gateway/main/examples/docker-compose/basic/docker-compose.yml
        curl -O https://raw.githubusercontent.com/inference-gateway/inference-gateway/main/examples/docker-compose/basic/.env.example
        mv .env.example .env

        # Edit .env with your API keys
        # Start the gateway
        docker compose up -d
        ```

        For more installation options and documentation, visit the [README](https://github.com/inference-gateway/inference-gateway#installation).
      successCommentCondition: 'false'
      labels:
        - "<%= nextRelease.channel === 'rc' ? 'prerelease' : 'release' %>"
        - "<%= nextRelease.channel === 'rc' ? 'rc' : '' %>"

  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - config/meta.go
        - charts/inference-gateway/Chart.yaml
      message: "chore(release): 🔖 ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
