---
version: '3'

tasks:
  default:
    desc: 'Show available tasks'
    cmds:
      - task --list

  mcp:schema:download:
    desc: 'Download the latest MCP schema'
    cmds:
      - curl -o mcp/mcp-schema.json https://raw.githubusercontent.com/inference-gateway/schemas/refs/heads/main/mcp/mcp-schema.json
      - curl -o mcp/mcp-schema.yaml https://raw.githubusercontent.com/inference-gateway/schemas/refs/heads/main/mcp/mcp-schema.yaml
      - task: format

  install:generator:
    desc: 'Install the generator tool'
    cmds:
      - GOBIN=${PWD}/bin go install github.com/inference-gateway/tools/cmd/generator@v0.1.2

  generate:
    desc: 'Generate the gateway from OpenAPI Spec'
    deps:
      - install:generator
    cmds:
      - go run cmd/generate/main.go -type ProvidersClientConfig -output providers/client/client.go
      - go run cmd/generate/main.go -type ProvidersConstants -output providers/constants/constants.go
      - go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest --config=.oapi-codegen.yaml -o providers/types/common_types.go openapi.yaml
      - sed -i '' 's/interface{}/any/g' providers/types/common_types.go
      - go run cmd/generate/main.go -type Providers -output providers/transformers
      - go run cmd/generate/main.go -type ProviderRegistry -output providers/registry/registry.go
      - go run cmd/generate/main.go -type Config -output config/config.go
      - go run cmd/generate/main.go -type MD -output Configurations.md
      - go run cmd/generate/main.go -type HelmSecret -output charts/inference-gateway/templates/secrets-defaults.yaml
      - go run cmd/generate/main.go -type HelmConfigMap -output charts/inference-gateway/templates/configmap-defaults.yaml
      - go run cmd/generate/main.go -type HelmValues -output charts/inference-gateway/values.yaml
      - go run cmd/generate/main.go -type Env -output examples/docker-compose/basic/.env.example
      - go run cmd/generate/main.go -type Env -output examples/docker-compose/hybrid/.env.example
      - go run cmd/generate/main.go -type Env -output examples/docker-compose/tools/.env.example
      - go run cmd/generate/main.go -type Env -output examples/docker-compose/ui/.env.backend.example
      - go run cmd/generate/main.go -type Env -output examples/docker-compose/authentication/.env.example
      - go run cmd/generate/main.go -type Env -output examples/docker-compose/mcp/.env.example
      - go run cmd/generate/main.go -type Env -output examples/docker-compose/monitoring/.env.example
      - ./bin/generator -generator jsonrpc -package mcp mcp/mcp-schema.yaml mcp/generated_types.go
      - go generate ./providers/... ./api/... ./otel/... ./logger/...  ./mcp/...
      - task: format
      - echo "✅ Codegen completed successfully!"

  tidy:
    desc: 'Tidy the gateway'
    cmds:
      - find . -name 'go.mod' -execdir go mod tidy \;

  build:
    desc: 'Build the gateway'
    cmds:
      - go build -o bin/inference-gateway cmd/gateway/main.go

  build:container:
    desc: 'Build the gateway container'
    cmds:
      - docker build -t inference-gateway .

  run:
    desc: 'Run the gateway'
    cmds:
      - go run cmd/gateway/main.go

  format:
    desc: 'Format the code'
    cmds:
      - prettier --write .
      - go fmt ./...

  lint:
    desc: 'Run Go static analysis and linting'
    cmds:
      - golangci-lint run
      - markdownlint . --ignore CHANGELOG.md --ignore '**/node_modules/**' --ignore Configurations.md --fix

  openapi:lint:
    desc: 'Lint OpenAPI spec'
    cmds:
      - npx @stoplight/spectral@6.5.0 lint --verbose openapi.yaml

  openapi:download:
    desc: 'Download the latest OpenAPI Spec'
    cmds:
      - curl -o openapi.yaml https://raw.githubusercontent.com/inference-gateway/schemas/refs/heads/main/openapi.yaml

  test:
    desc: 'Run tests'
    cmds:
      - go test -v ./...

  benchmark:
    desc: 'Run benchmarks'
    cmds:
      - go test -bench=. -run=^$ -benchmem -benchtime=100x -count=20 ./tests/...

  pre-commit:install:
    desc: 'Install pre-commit hooks'
    cmds:
      - echo "Installing pre-commit checks..."
      - ln -sf ../../scripts/pre-commit-check.sh .git/hooks/pre-commit
      - chmod +x .git/hooks/pre-commit
      - echo "✅ Pre-commit hook installed successfully!"

  pre-commit:uninstall:
    desc: 'Uninstall pre-commit hooks'
    cmds:
      - rm -f .git/hooks/pre-commit
      - echo "✅ Pre-commit hook uninstalled successfully!"

  package:
    desc: 'Package the gateway'
    cmds:
      - docker build -t inference-gateway .

  release-dry-run:
    desc: 'Run a dry-run of both semantic-release and goreleaser'
    cmds:
      - echo "Running semantic-release dry run..."
      - semantic-release --dry-run
      - echo "Running goreleaser dry run..."
      - goreleaser release --config .goreleaser.yaml --clean --snapshot --verbose
