apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inference-gateway-a2a-discovery
  labels:
    app.kubernetes.io/name: inference-gateway
    app.kubernetes.io/instance: inference-gateway
rules:
  - apiGroups:
      - core.inference-gateway.com
    resources:
      - agents
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inference-gateway-a2a-discovery
  labels:
    app.kubernetes.io/name: inference-gateway
    app.kubernetes.io/instance: inference-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: inference-gateway-a2a-discovery
subjects:
  - kind: ServiceAccount
    name: inference-gateway
    namespace: inference-gateway
