// Code generated by MockGen. DO NOT EDIT.
// Source: agent.go
//
// Generated by this command:
//
//	mockgen -source=agent.go -destination=../../tests/mocks/mcp/agent.go -package=mcpmocks -typed
//

// Package mcpmocks is a generated GoMock package.
package mcpmocks

import (
	context "context"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	core "github.com/inference-gateway/inference-gateway/providers/core"
	types "github.com/inference-gateway/inference-gateway/providers/types"
	gomock "go.uber.org/mock/gomock"
)

// MockAgent is a mock of Agent interface.
type MockAgent struct {
	ctrl     *gomock.Controller
	recorder *MockAgentMockRecorder
	isgomock struct{}
}

// MockAgentMockRecorder is the mock recorder for MockAgent.
type MockAgentMockRecorder struct {
	mock *MockAgent
}

// NewMockAgent creates a new mock instance.
func NewMockAgent(ctrl *gomock.Controller) *MockAgent {
	mock := &MockAgent{ctrl: ctrl}
	mock.recorder = &MockAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgent) EXPECT() *MockAgentMockRecorder {
	return m.recorder
}

// ExecuteTools mocks base method.
func (m *MockAgent) ExecuteTools(ctx context.Context, toolCalls []types.ChatCompletionMessageToolCall) ([]types.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteTools", ctx, toolCalls)
	ret0, _ := ret[0].([]types.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteTools indicates an expected call of ExecuteTools.
func (mr *MockAgentMockRecorder) ExecuteTools(ctx, toolCalls any) *MockAgentExecuteToolsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTools", reflect.TypeOf((*MockAgent)(nil).ExecuteTools), ctx, toolCalls)
	return &MockAgentExecuteToolsCall{Call: call}
}

// MockAgentExecuteToolsCall wrap *gomock.Call
type MockAgentExecuteToolsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAgentExecuteToolsCall) Return(arg0 []types.Message, arg1 error) *MockAgentExecuteToolsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAgentExecuteToolsCall) Do(f func(context.Context, []types.ChatCompletionMessageToolCall) ([]types.Message, error)) *MockAgentExecuteToolsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAgentExecuteToolsCall) DoAndReturn(f func(context.Context, []types.ChatCompletionMessageToolCall) ([]types.Message, error)) *MockAgentExecuteToolsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Run mocks base method.
func (m *MockAgent) Run(ctx context.Context, request *types.CreateChatCompletionRequest, response *types.CreateChatCompletionResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, request, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockAgentMockRecorder) Run(ctx, request, response any) *MockAgentRunCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockAgent)(nil).Run), ctx, request, response)
	return &MockAgentRunCall{Call: call}
}

// MockAgentRunCall wrap *gomock.Call
type MockAgentRunCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAgentRunCall) Return(arg0 error) *MockAgentRunCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAgentRunCall) Do(f func(context.Context, *types.CreateChatCompletionRequest, *types.CreateChatCompletionResponse) error) *MockAgentRunCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAgentRunCall) DoAndReturn(f func(context.Context, *types.CreateChatCompletionRequest, *types.CreateChatCompletionResponse) error) *MockAgentRunCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RunWithStream mocks base method.
func (m *MockAgent) RunWithStream(ctx context.Context, middlewareStreamCh chan []byte, c *gin.Context, body *types.CreateChatCompletionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunWithStream", ctx, middlewareStreamCh, c, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunWithStream indicates an expected call of RunWithStream.
func (mr *MockAgentMockRecorder) RunWithStream(ctx, middlewareStreamCh, c, body any) *MockAgentRunWithStreamCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWithStream", reflect.TypeOf((*MockAgent)(nil).RunWithStream), ctx, middlewareStreamCh, c, body)
	return &MockAgentRunWithStreamCall{Call: call}
}

// MockAgentRunWithStreamCall wrap *gomock.Call
type MockAgentRunWithStreamCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *MockAgentRunWithStreamCall) Return(arg0 error) *MockAgentRunWithStreamCall {
	c_2.Call = c_2.Call.Return(arg0)
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *MockAgentRunWithStreamCall) Do(f func(context.Context, chan []byte, *gin.Context, *types.CreateChatCompletionRequest) error) *MockAgentRunWithStreamCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *MockAgentRunWithStreamCall) DoAndReturn(f func(context.Context, chan []byte, *gin.Context, *types.CreateChatCompletionRequest) error) *MockAgentRunWithStreamCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}

// SetModel mocks base method.
func (m *MockAgent) SetModel(model *string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetModel", model)
}

// SetModel indicates an expected call of SetModel.
func (mr *MockAgentMockRecorder) SetModel(model any) *MockAgentSetModelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetModel", reflect.TypeOf((*MockAgent)(nil).SetModel), model)
	return &MockAgentSetModelCall{Call: call}
}

// MockAgentSetModelCall wrap *gomock.Call
type MockAgentSetModelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAgentSetModelCall) Return() *MockAgentSetModelCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAgentSetModelCall) Do(f func(*string)) *MockAgentSetModelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAgentSetModelCall) DoAndReturn(f func(*string)) *MockAgentSetModelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetProvider mocks base method.
func (m *MockAgent) SetProvider(provider core.IProvider) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetProvider", provider)
}

// SetProvider indicates an expected call of SetProvider.
func (mr *MockAgentMockRecorder) SetProvider(provider any) *MockAgentSetProviderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProvider", reflect.TypeOf((*MockAgent)(nil).SetProvider), provider)
	return &MockAgentSetProviderCall{Call: call}
}

// MockAgentSetProviderCall wrap *gomock.Call
type MockAgentSetProviderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAgentSetProviderCall) Return() *MockAgentSetProviderCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAgentSetProviderCall) Do(f func(core.IProvider)) *MockAgentSetProviderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAgentSetProviderCall) DoAndReturn(f func(core.IProvider)) *MockAgentSetProviderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
