// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=../../tests/mocks/mcp/client.go -package=mcpmocks -typed
//

// Package mcpmocks is a generated GoMock package.
package mcpmocks

import (
	context "context"
	reflect "reflect"

	mcp "github.com/inference-gateway/inference-gateway/internal/mcp"
	types "github.com/inference-gateway/inference-gateway/providers/types"
	gomock "go.uber.org/mock/gomock"
)

// MockMCPClientInterface is a mock of MCPClientInterface interface.
type MockMCPClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMCPClientInterfaceMockRecorder
	isgomock struct{}
}

// MockMCPClientInterfaceMockRecorder is the mock recorder for MockMCPClientInterface.
type MockMCPClientInterfaceMockRecorder struct {
	mock *MockMCPClientInterface
}

// NewMockMCPClientInterface creates a new mock instance.
func NewMockMCPClientInterface(ctrl *gomock.Controller) *MockMCPClientInterface {
	mock := &MockMCPClientInterface{ctrl: ctrl}
	mock.recorder = &MockMCPClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMCPClientInterface) EXPECT() *MockMCPClientInterfaceMockRecorder {
	return m.recorder
}

// BuildSSEFallbackURL mocks base method.
func (m *MockMCPClientInterface) BuildSSEFallbackURL(serverURL string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildSSEFallbackURL", serverURL)
	ret0, _ := ret[0].(string)
	return ret0
}

// BuildSSEFallbackURL indicates an expected call of BuildSSEFallbackURL.
func (mr *MockMCPClientInterfaceMockRecorder) BuildSSEFallbackURL(serverURL any) *MockMCPClientInterfaceBuildSSEFallbackURLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildSSEFallbackURL", reflect.TypeOf((*MockMCPClientInterface)(nil).BuildSSEFallbackURL), serverURL)
	return &MockMCPClientInterfaceBuildSSEFallbackURLCall{Call: call}
}

// MockMCPClientInterfaceBuildSSEFallbackURLCall wrap *gomock.Call
type MockMCPClientInterfaceBuildSSEFallbackURLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMCPClientInterfaceBuildSSEFallbackURLCall) Return(arg0 string) *MockMCPClientInterfaceBuildSSEFallbackURLCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMCPClientInterfaceBuildSSEFallbackURLCall) Do(f func(string) string) *MockMCPClientInterfaceBuildSSEFallbackURLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMCPClientInterfaceBuildSSEFallbackURLCall) DoAndReturn(f func(string) string) *MockMCPClientInterfaceBuildSSEFallbackURLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ConvertMCPToolsToChatCompletionTools mocks base method.
func (m *MockMCPClientInterface) ConvertMCPToolsToChatCompletionTools(arg0 []mcp.Tool) []types.ChatCompletionTool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertMCPToolsToChatCompletionTools", arg0)
	ret0, _ := ret[0].([]types.ChatCompletionTool)
	return ret0
}

// ConvertMCPToolsToChatCompletionTools indicates an expected call of ConvertMCPToolsToChatCompletionTools.
func (mr *MockMCPClientInterfaceMockRecorder) ConvertMCPToolsToChatCompletionTools(arg0 any) *MockMCPClientInterfaceConvertMCPToolsToChatCompletionToolsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertMCPToolsToChatCompletionTools", reflect.TypeOf((*MockMCPClientInterface)(nil).ConvertMCPToolsToChatCompletionTools), arg0)
	return &MockMCPClientInterfaceConvertMCPToolsToChatCompletionToolsCall{Call: call}
}

// MockMCPClientInterfaceConvertMCPToolsToChatCompletionToolsCall wrap *gomock.Call
type MockMCPClientInterfaceConvertMCPToolsToChatCompletionToolsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMCPClientInterfaceConvertMCPToolsToChatCompletionToolsCall) Return(arg0 []types.ChatCompletionTool) *MockMCPClientInterfaceConvertMCPToolsToChatCompletionToolsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMCPClientInterfaceConvertMCPToolsToChatCompletionToolsCall) Do(f func([]mcp.Tool) []types.ChatCompletionTool) *MockMCPClientInterfaceConvertMCPToolsToChatCompletionToolsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMCPClientInterfaceConvertMCPToolsToChatCompletionToolsCall) DoAndReturn(f func([]mcp.Tool) []types.ChatCompletionTool) *MockMCPClientInterfaceConvertMCPToolsToChatCompletionToolsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ExecuteTool mocks base method.
func (m *MockMCPClientInterface) ExecuteTool(ctx context.Context, request mcp.Request, serverURL string) (*mcp.CallToolResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteTool", ctx, request, serverURL)
	ret0, _ := ret[0].(*mcp.CallToolResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteTool indicates an expected call of ExecuteTool.
func (mr *MockMCPClientInterfaceMockRecorder) ExecuteTool(ctx, request, serverURL any) *MockMCPClientInterfaceExecuteToolCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTool", reflect.TypeOf((*MockMCPClientInterface)(nil).ExecuteTool), ctx, request, serverURL)
	return &MockMCPClientInterfaceExecuteToolCall{Call: call}
}

// MockMCPClientInterfaceExecuteToolCall wrap *gomock.Call
type MockMCPClientInterfaceExecuteToolCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMCPClientInterfaceExecuteToolCall) Return(arg0 *mcp.CallToolResult, arg1 error) *MockMCPClientInterfaceExecuteToolCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMCPClientInterfaceExecuteToolCall) Do(f func(context.Context, mcp.Request, string) (*mcp.CallToolResult, error)) *MockMCPClientInterfaceExecuteToolCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMCPClientInterfaceExecuteToolCall) DoAndReturn(f func(context.Context, mcp.Request, string) (*mcp.CallToolResult, error)) *MockMCPClientInterfaceExecuteToolCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAllChatCompletionTools mocks base method.
func (m *MockMCPClientInterface) GetAllChatCompletionTools() []types.ChatCompletionTool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllChatCompletionTools")
	ret0, _ := ret[0].([]types.ChatCompletionTool)
	return ret0
}

// GetAllChatCompletionTools indicates an expected call of GetAllChatCompletionTools.
func (mr *MockMCPClientInterfaceMockRecorder) GetAllChatCompletionTools() *MockMCPClientInterfaceGetAllChatCompletionToolsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllChatCompletionTools", reflect.TypeOf((*MockMCPClientInterface)(nil).GetAllChatCompletionTools))
	return &MockMCPClientInterfaceGetAllChatCompletionToolsCall{Call: call}
}

// MockMCPClientInterfaceGetAllChatCompletionToolsCall wrap *gomock.Call
type MockMCPClientInterfaceGetAllChatCompletionToolsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMCPClientInterfaceGetAllChatCompletionToolsCall) Return(arg0 []types.ChatCompletionTool) *MockMCPClientInterfaceGetAllChatCompletionToolsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMCPClientInterfaceGetAllChatCompletionToolsCall) Do(f func() []types.ChatCompletionTool) *MockMCPClientInterfaceGetAllChatCompletionToolsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMCPClientInterfaceGetAllChatCompletionToolsCall) DoAndReturn(f func() []types.ChatCompletionTool) *MockMCPClientInterfaceGetAllChatCompletionToolsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAllServerStatuses mocks base method.
func (m *MockMCPClientInterface) GetAllServerStatuses() map[string]mcp.ServerStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllServerStatuses")
	ret0, _ := ret[0].(map[string]mcp.ServerStatus)
	return ret0
}

// GetAllServerStatuses indicates an expected call of GetAllServerStatuses.
func (mr *MockMCPClientInterfaceMockRecorder) GetAllServerStatuses() *MockMCPClientInterfaceGetAllServerStatusesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllServerStatuses", reflect.TypeOf((*MockMCPClientInterface)(nil).GetAllServerStatuses))
	return &MockMCPClientInterfaceGetAllServerStatusesCall{Call: call}
}

// MockMCPClientInterfaceGetAllServerStatusesCall wrap *gomock.Call
type MockMCPClientInterfaceGetAllServerStatusesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMCPClientInterfaceGetAllServerStatusesCall) Return(arg0 map[string]mcp.ServerStatus) *MockMCPClientInterfaceGetAllServerStatusesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMCPClientInterfaceGetAllServerStatusesCall) Do(f func() map[string]mcp.ServerStatus) *MockMCPClientInterfaceGetAllServerStatusesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMCPClientInterfaceGetAllServerStatusesCall) DoAndReturn(f func() map[string]mcp.ServerStatus) *MockMCPClientInterfaceGetAllServerStatusesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetServerForTool mocks base method.
func (m *MockMCPClientInterface) GetServerForTool(toolName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerForTool", toolName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerForTool indicates an expected call of GetServerForTool.
func (mr *MockMCPClientInterfaceMockRecorder) GetServerForTool(toolName any) *MockMCPClientInterfaceGetServerForToolCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerForTool", reflect.TypeOf((*MockMCPClientInterface)(nil).GetServerForTool), toolName)
	return &MockMCPClientInterfaceGetServerForToolCall{Call: call}
}

// MockMCPClientInterfaceGetServerForToolCall wrap *gomock.Call
type MockMCPClientInterfaceGetServerForToolCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMCPClientInterfaceGetServerForToolCall) Return(arg0 string, arg1 error) *MockMCPClientInterfaceGetServerForToolCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMCPClientInterfaceGetServerForToolCall) Do(f func(string) (string, error)) *MockMCPClientInterfaceGetServerForToolCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMCPClientInterfaceGetServerForToolCall) DoAndReturn(f func(string) (string, error)) *MockMCPClientInterfaceGetServerForToolCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetServerTools mocks base method.
func (m *MockMCPClientInterface) GetServerTools(serverURL string) ([]mcp.Tool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerTools", serverURL)
	ret0, _ := ret[0].([]mcp.Tool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerTools indicates an expected call of GetServerTools.
func (mr *MockMCPClientInterfaceMockRecorder) GetServerTools(serverURL any) *MockMCPClientInterfaceGetServerToolsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerTools", reflect.TypeOf((*MockMCPClientInterface)(nil).GetServerTools), serverURL)
	return &MockMCPClientInterfaceGetServerToolsCall{Call: call}
}

// MockMCPClientInterfaceGetServerToolsCall wrap *gomock.Call
type MockMCPClientInterfaceGetServerToolsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMCPClientInterfaceGetServerToolsCall) Return(arg0 []mcp.Tool, arg1 error) *MockMCPClientInterfaceGetServerToolsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMCPClientInterfaceGetServerToolsCall) Do(f func(string) ([]mcp.Tool, error)) *MockMCPClientInterfaceGetServerToolsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMCPClientInterfaceGetServerToolsCall) DoAndReturn(f func(string) ([]mcp.Tool, error)) *MockMCPClientInterfaceGetServerToolsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetServers mocks base method.
func (m *MockMCPClientInterface) GetServers() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServers")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetServers indicates an expected call of GetServers.
func (mr *MockMCPClientInterfaceMockRecorder) GetServers() *MockMCPClientInterfaceGetServersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServers", reflect.TypeOf((*MockMCPClientInterface)(nil).GetServers))
	return &MockMCPClientInterfaceGetServersCall{Call: call}
}

// MockMCPClientInterfaceGetServersCall wrap *gomock.Call
type MockMCPClientInterfaceGetServersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMCPClientInterfaceGetServersCall) Return(arg0 []string) *MockMCPClientInterfaceGetServersCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMCPClientInterfaceGetServersCall) Do(f func() []string) *MockMCPClientInterfaceGetServersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMCPClientInterfaceGetServersCall) DoAndReturn(f func() []string) *MockMCPClientInterfaceGetServersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InitializeAll mocks base method.
func (m *MockMCPClientInterface) InitializeAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitializeAll indicates an expected call of InitializeAll.
func (mr *MockMCPClientInterfaceMockRecorder) InitializeAll(ctx any) *MockMCPClientInterfaceInitializeAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeAll", reflect.TypeOf((*MockMCPClientInterface)(nil).InitializeAll), ctx)
	return &MockMCPClientInterfaceInitializeAllCall{Call: call}
}

// MockMCPClientInterfaceInitializeAllCall wrap *gomock.Call
type MockMCPClientInterfaceInitializeAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMCPClientInterfaceInitializeAllCall) Return(arg0 error) *MockMCPClientInterfaceInitializeAllCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMCPClientInterfaceInitializeAllCall) Do(f func(context.Context) error) *MockMCPClientInterfaceInitializeAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMCPClientInterfaceInitializeAllCall) DoAndReturn(f func(context.Context) error) *MockMCPClientInterfaceInitializeAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsInitialized mocks base method.
func (m *MockMCPClientInterface) IsInitialized() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInitialized")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsInitialized indicates an expected call of IsInitialized.
func (mr *MockMCPClientInterfaceMockRecorder) IsInitialized() *MockMCPClientInterfaceIsInitializedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInitialized", reflect.TypeOf((*MockMCPClientInterface)(nil).IsInitialized))
	return &MockMCPClientInterfaceIsInitializedCall{Call: call}
}

// MockMCPClientInterfaceIsInitializedCall wrap *gomock.Call
type MockMCPClientInterfaceIsInitializedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMCPClientInterfaceIsInitializedCall) Return(arg0 bool) *MockMCPClientInterfaceIsInitializedCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMCPClientInterfaceIsInitializedCall) Do(f func() bool) *MockMCPClientInterfaceIsInitializedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMCPClientInterfaceIsInitializedCall) DoAndReturn(f func() bool) *MockMCPClientInterfaceIsInitializedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StartStatusPolling mocks base method.
func (m *MockMCPClientInterface) StartStatusPolling(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartStatusPolling", ctx)
}

// StartStatusPolling indicates an expected call of StartStatusPolling.
func (mr *MockMCPClientInterfaceMockRecorder) StartStatusPolling(ctx any) *MockMCPClientInterfaceStartStatusPollingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartStatusPolling", reflect.TypeOf((*MockMCPClientInterface)(nil).StartStatusPolling), ctx)
	return &MockMCPClientInterfaceStartStatusPollingCall{Call: call}
}

// MockMCPClientInterfaceStartStatusPollingCall wrap *gomock.Call
type MockMCPClientInterfaceStartStatusPollingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMCPClientInterfaceStartStatusPollingCall) Return() *MockMCPClientInterfaceStartStatusPollingCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMCPClientInterfaceStartStatusPollingCall) Do(f func(context.Context)) *MockMCPClientInterfaceStartStatusPollingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMCPClientInterfaceStartStatusPollingCall) DoAndReturn(f func(context.Context)) *MockMCPClientInterfaceStartStatusPollingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StopBackgroundReconnection mocks base method.
func (m *MockMCPClientInterface) StopBackgroundReconnection() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopBackgroundReconnection")
}

// StopBackgroundReconnection indicates an expected call of StopBackgroundReconnection.
func (mr *MockMCPClientInterfaceMockRecorder) StopBackgroundReconnection() *MockMCPClientInterfaceStopBackgroundReconnectionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopBackgroundReconnection", reflect.TypeOf((*MockMCPClientInterface)(nil).StopBackgroundReconnection))
	return &MockMCPClientInterfaceStopBackgroundReconnectionCall{Call: call}
}

// MockMCPClientInterfaceStopBackgroundReconnectionCall wrap *gomock.Call
type MockMCPClientInterfaceStopBackgroundReconnectionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMCPClientInterfaceStopBackgroundReconnectionCall) Return() *MockMCPClientInterfaceStopBackgroundReconnectionCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMCPClientInterfaceStopBackgroundReconnectionCall) Do(f func()) *MockMCPClientInterfaceStopBackgroundReconnectionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMCPClientInterfaceStopBackgroundReconnectionCall) DoAndReturn(f func()) *MockMCPClientInterfaceStopBackgroundReconnectionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StopStatusPolling mocks base method.
func (m *MockMCPClientInterface) StopStatusPolling() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopStatusPolling")
}

// StopStatusPolling indicates an expected call of StopStatusPolling.
func (mr *MockMCPClientInterfaceMockRecorder) StopStatusPolling() *MockMCPClientInterfaceStopStatusPollingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopStatusPolling", reflect.TypeOf((*MockMCPClientInterface)(nil).StopStatusPolling))
	return &MockMCPClientInterfaceStopStatusPollingCall{Call: call}
}

// MockMCPClientInterfaceStopStatusPollingCall wrap *gomock.Call
type MockMCPClientInterfaceStopStatusPollingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMCPClientInterfaceStopStatusPollingCall) Return() *MockMCPClientInterfaceStopStatusPollingCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMCPClientInterfaceStopStatusPollingCall) Do(f func()) *MockMCPClientInterfaceStopStatusPollingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMCPClientInterfaceStopStatusPollingCall) DoAndReturn(f func()) *MockMCPClientInterfaceStopStatusPollingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
